### ISSUE TITLE
I want twrp

### ISSUE THREAD

**Issue by EngRudhy** [Vloupmon/TWRP_Realme_RMX3085#1]
Could you please send me pre-built version of this I need it 
please help me out I want TWRP.IMG 

I need TWRP for realme 8

**Comment by alchimestre** [comment]
I don't have a working version of TWRP, the build is broken, it's just a work-in-progress thing

**Comment by EngRudhy** [comment]
@Vloupmon Hi I have create a twrp for this device and it is working but having some isuue 
also I could root my device throw the twrp 

if you want to take a look

**Comment by alchimestre** [comment]
@EngRudhy Thanks for thinking about me, I'd love to look at your TWRP tree if you have one. Can you put it on a public repo ? Thanks.

**Comment by EngRudhy** [comment]
@Vloupmon 
this is the repo
https://github.com/skyhuppa/Realme_8_RMX3085

**Comment by alchimestre** [comment]
Thanks, I'll try a build when I got free time.
